version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/repo
          keys:
            - demo-java-{{ checksum "pom.xml" }}
            - demo-java-
      - run:
          name: "Install and Launch Sauce Connect Tunnel"
          background: true
          command: |
            sudo apt-get install lsof
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc --pidfile /tmp/sc.pid -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -i demo-java-tunnel --no-remove-colliding-tunnels
      - run:
          name: "Setup Maven Dependencies"
          command: |
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-java-{{ checksum "pom.xml" }}
      - run:
          name: "Run Maven Tests"
          command: |
            while ! lsof -i:4445 -t; do sleep 3; done
            mvn clean test
      - run:
          name: "Shut Down Sauce Connect Tunnel"
          command: |
            kill -9 `cat /tmp/sc.pid`
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-0.0.1-SNAPSHOT.jar