version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/repo
          keys:
            - demo-java-{{ checksum "pom.xml" }}
            - demo-java-
      - run:
          name: "Setup Maven Dependencies"
          command: |
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-java-{{ checksum "pom.xml" }}
      - run:
          name: "Install and Launch Sauce Connect Tunnel"
          background: true
          command: |
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY}
            wget --retry-connrefused --no-check-certificate -T 90 localhost:4445  # wait for app to be ready
      - run:
          name: "Run Maven Tests"
          command: |
            mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-0.0.1-SNAPSHOT.jar